# Generated by Django 5.1.7 on 2025-08-11 07:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='interested_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
